---
- name: Include create tasks
  include_tasks: create.yml
  when: sg_state | default('present') == 'present'

- name: Include delete tasks
  include_tasks: delete.yml
  when: sg_state | default('present') == 'absent'
