#SPDX-License-Identifier: MIT-0
---
# defaults file for nginx
project_name: "ansible-ohm-ec2"
app_environment: "production"
nginx_show_hostname: true
ec2_instance_type: "t3.micro"
aws_region: "ap-southeast-7"
nginx_document_root: "/var/www/html"
nginx_listen_port: 80
health_check_path: "/health"
nginx_config_path: /etc/nginx/sites-available/backend