#SPDX-License-Identifier: MIT-0
---
# defaults file for ec2_instance
aws_region: ap-southeast-7
instance_name: ansible-ohm-ec2
instance_type: t3.micro

ami_id: ami-0630fc0638df720c6
key_name: test-key-ohm
ssh_private_key_file: /home/exit0x1/ansible-playground/keys/ansible-ohm-key.pem

subnet_id: subnet-0b75fdf2e50f4a191
security_group:
  - "{{ result_security_group.group_id }}"

ec2_tags:
  project: ansible-ohm-ec2-tag